version: "3.8"
services:
  american-school-next:
    container_name: american-school-next-local
    image: american-school-next-local
    build:
      context: ../..
      dockerfile: scripts/docker/dockerfile
    restart: always
    ports:
      - "9090:9090"
